### ISSUE TITLE
Upload Image failed with v2.0.18

### ISSUE THREAD

**Issue by TennisAndy** [flutterchina/dio#204]
## Steps to Reproduce
后台为微信小程序服务器Wafer-Node-SDK, 通过upload()接口上传。
微信小程序上传正常，接口调试工具上传正常，android kotlin Fuel v1.130上传正常，Flutter Dio v2.0.18始终无法上传成功！

void uploadImage() async {
    print('[uploadImage] localImage ${localImage.lengthSync()}');
    FormData data = FormData.from({
      'file': UploadFileInfo(localImage, 'img_${DateTime.now().millisecondsSinceEpoch}.png')
    });
    var dio = Dio();
    dio.options.headers["x-wx-skey"] = Application.curAccount.token;

    dio.interceptors.add(InterceptorsWrapper(onRequest: (RequestOptions options) {
      // Do something before request is sent
      return options; //continue
    }, onResponse: (Response rsp) {
      // Do something with response data
      print('[onSuccess] $rsp');
      if (rsp.data["code"] == 0)
        return rsp.data["data"];
      else
        return rsp;
    }, onError: (DioError e) {
      print('[onError] $e');
      // Do something with response error
      return e; //continue
    }));
    try {
      var response = await dio.post(ApiProvider.API_UPLOAD_FILE, data: data);
      print('[uploadImage] $response');
    } catch (e) {
      print('[uploadImage] $e');
    }
  }

## Logs
I/flutter ( 3069): [uploadImage] localImage 58667
I/flutter ( 3069): [onError] DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received, uri = http://22786vp873.iok.la/weapp/upload
I/flutter ( 3069): [uploadImage] DioError [DioErrorType.DEFAULT]: HttpException: Connection closed before full header was received, uri = http://22786vp873.iok.la/weapp/upload

请求大神帮忙！

**Comment by wendux** [comment]
我本地测试了一下貌似没什么问题，我的测试代码如下：
```dart
  Dio dio = Dio();
  dio.interceptors.add(LogInterceptor(requestBody: true));
  dio.post("http://22786vp873.iok.la/weapp/upload", data: FormData.from({
  "file": UploadFileInfo.fromBytes(utf8.encode("hello"), "xx.txt"),
  }));

```
日志：
```
*** Request ***
uri: http://22786vp873.iok.la/weapp/upload
method: POST
contentType: application/json; charset=utf-8
responseType: ResponseType.json
followRedirects: true
connectTimeout: 0
receiveTimeout: 0
extra: {}
header: 
  content-type:multipart/form-data; boundary=--dio-boundary-3331351018
data:
----dio-boundary-3331351018
Content-Disposition: form-data; name="file"; filename="xx.txt"
Content-Type: application/octet-stream

hello
----dio-boundary-3331351018--

*** Response ***
uri: http://22786vp873.iok.la/weapp/upload
statusCode: 200
headers:
 connection: keep-alive
 content-type: application/json; charset=utf-8
 date: Tue, 05 Mar 2019 08:40:24 GMT
 access-control-allow-origin: *
 access-control-allow-methods: GET,HEAD,PUT,POST,DELETE
 content-length: 38
```
如果是在手机上，可以看看网络是否通的或者有没有访问网络的权限；
